from PyQt5 import QtCore, QtGui, QtWidgets
import img_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(755, 846)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 846))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/filmesIMG/ufs_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background: black;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(755, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(12000000, 1200000))
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 755, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 60))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame.setStyleSheet("background-color: rgb(59, 59, 59);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/filmesIMG/ufs_logo.png"))
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10, 0, QtCore.Qt.AlignLeft)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 60, 755, 744))
        self.frame_2.setMinimumSize(QtCore.QSize(755, 744))
        self.frame_2.setMaximumSize(QtCore.QSize(755, 744))
        self.frame_2.setStyleSheet("background-color: rgb(45, 64, 100);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.page)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 734, 1200))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 1200))
        self.scrollAreaWidgetContents.setStyleSheet("QLabel\n"
"{\n"
"border: 3px solid black;\n"
"}\n"
"QLabel:hover\n"
"{\n"
" border: 3px solid yellow;\n"
"}")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.cartazLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.cartazLabel.setGeometry(QtCore.QRect(240, 10, 241, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.cartazLabel.setFont(font)
        self.cartazLabel.setStyleSheet("QLabel\n"
"{\n"
"border:0px solid black;\n"
"}\n"
"QLabel:hover\n"
"{\n"
" border: 0px solid yellow;\n"
"}")
        self.cartazLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cartazLabel.setObjectName("cartazLabel")
        self.filme_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.filme_1.setGeometry(QtCore.QRect(15, 130, 201, 281))
        self.filme_1.setStyleSheet("")
        self.filme_1.setText("")
        self.filme_1.setPixmap(QtGui.QPixmap(":/filmesIMG/images.jpg"))
        self.filme_1.setScaledContents(True)
        self.filme_1.setObjectName("filme_1")
        self.filme_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.filme_2.setGeometry(QtCore.QRect(265, 130, 201, 281))
        self.filme_2.setStyleSheet("")
        self.filme_2.setText("")
        self.filme_2.setPixmap(QtGui.QPixmap(":/filmesIMG/images_1.jpg"))
        self.filme_2.setScaledContents(True)
        self.filme_2.setObjectName("filme_2")
        self.filme_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.filme_3.setGeometry(QtCore.QRect(515, 130, 201, 281))
        self.filme_3.setStyleSheet("")
        self.filme_3.setText("")
        self.filme_3.setPixmap(QtGui.QPixmap(":/filmesIMG/Sonic_the_Hedgehog_2019.jpg"))
        self.filme_3.setScaledContents(True)
        self.filme_3.setObjectName("filme_3")
        self.filme_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.filme_4.setGeometry(QtCore.QRect(15, 460, 201, 281))
        self.filme_4.setStyleSheet("")
        self.filme_4.setText("")
        self.filme_4.setPixmap(QtGui.QPixmap(":/filmesIMG/3152202.jpg"))
        self.filme_4.setScaledContents(True)
        self.filme_4.setObjectName("filme_4")
        self.filme_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.filme_5.setGeometry(QtCore.QRect(265, 460, 201, 281))
        self.filme_5.setStyleSheet("")
        self.filme_5.setText("")
        self.filme_5.setPixmap(QtGui.QPixmap(":/filmesIMG/4198735.jpg"))
        self.filme_5.setScaledContents(True)
        self.filme_5.setObjectName("filme_5")
        self.filme_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.filme_6.setGeometry(QtCore.QRect(515, 460, 201, 281))
        self.filme_6.setStyleSheet("")
        self.filme_6.setText("")
        self.filme_6.setPixmap(QtGui.QPixmap(":/filmesIMG/escolha-ou-morra-poster.jpg"))
        self.filme_6.setScaledContents(True)
        self.filme_6.setObjectName("filme_6")
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setGeometry(QtCore.QRect(0, 90, 731, 20))
        self.label_11.setStyleSheet("QLabel\n"
"{\n"
"border: 0px solid black;\n"
"}\n"
"QLabel:hover\n"
"{\n"
" border: 0px solid yellow;\n"
"}")
        self.label_11.setObjectName("label_11")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(93, 93, 93);\n"
"color: white;\n"
"border: 2px solid black;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(93, 93, 93);\n"
"color: white;\n"
"border: 2px solid white;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:checked{\n"
"background-color: rgb(72, 171, 6);\n"
"color: white;\n"
"border: 2px solid white;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"")
        self.page_2.setObjectName("page_2")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.page_2)
        self.scrollArea_2.setGeometry(QtCore.QRect(-10, 0, 761, 741))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 742, 1200))
        self.scrollAreaWidgetContents_2.setMinimumSize(QtCore.QSize(0, 1200))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.scrollAreaWidgetContents_2)
        self.stackedWidget_2.setGeometry(QtCore.QRect(30, 300, 621, 371))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_horario_1 = QtWidgets.QWidget()
        self.page_horario_1.setObjectName("page_horario_1")
        self.frame_horario_1 = QtWidgets.QFrame(self.page_horario_1)
        self.frame_horario_1.setGeometry(QtCore.QRect(0, 10, 601, 341))
        self.frame_horario_1.setStyleSheet("QFrame{\n"
"background-color: rgb(59, 59, 59);\n"
"border: 2px solid black\n"
";}\n"
"")
        self.frame_horario_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_horario_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_horario_1.setObjectName("frame_horario_1")
        self.label = QtWidgets.QLabel(self.frame_horario_1)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("border: 0px solid black;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_horario_1)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: 0px solid black;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_horario_1)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border: 0px solid black;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_horario_1)
        self.label_4.setGeometry(QtCore.QRect(10, 220, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border: 0px solid black;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_horario_1)
        self.label_5.setGeometry(QtCore.QRect(10, 50, 581, 20))
        self.label_5.setStyleSheet("border: 0px solid black;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_horario_1)
        self.label_6.setGeometry(QtCore.QRect(10, 120, 581, 20))
        self.label_6.setStyleSheet("border: 0px solid black;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_horario_1)
        self.label_7.setGeometry(QtCore.QRect(10, 190, 581, 20))
        self.label_7.setStyleSheet("border: 0px solid black;")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_horario_1)
        self.label_8.setGeometry(QtCore.QRect(10, 290, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border: 0px solid black;")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_horario_1)
        self.label_9.setGeometry(QtCore.QRect(10, 260, 581, 20))
        self.label_9.setStyleSheet("border: 0px solid black;")
        self.label_9.setObjectName("label_9")
        self.stackedWidget_2.addWidget(self.page_horario_1)
        self.page_horario_2 = QtWidgets.QWidget()
        self.page_horario_2.setObjectName("page_horario_2")
        self.frame_horario_2 = QtWidgets.QFrame(self.page_horario_2)
        self.frame_horario_2.setGeometry(QtCore.QRect(20, 10, 601, 341))
        self.frame_horario_2.setStyleSheet("QFrame{\n"
"background-color: rgb(59, 59, 59);\n"
"border: 2px solid black\n"
";}\n"
"")
        self.frame_horario_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_horario_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_horario_2.setObjectName("frame_horario_2")
        self.label_48 = QtWidgets.QLabel(self.frame_horario_2)
        self.label_48.setGeometry(QtCore.QRect(10, 10, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("border: 0px solid black;")
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.frame_horario_2)
        self.label_49.setGeometry(QtCore.QRect(10, 80, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet("border: 0px solid black;")
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.frame_horario_2)
        self.label_50.setGeometry(QtCore.QRect(10, 150, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("border: 0px solid black;")
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.frame_horario_2)
        self.label_51.setGeometry(QtCore.QRect(10, 220, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setStyleSheet("border: 0px solid black;")
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.frame_horario_2)
        self.label_52.setGeometry(QtCore.QRect(10, 50, 581, 20))
        self.label_52.setStyleSheet("border: 0px solid black;")
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.frame_horario_2)
        self.label_53.setGeometry(QtCore.QRect(10, 120, 581, 20))
        self.label_53.setStyleSheet("border: 0px solid black;")
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.frame_horario_2)
        self.label_54.setGeometry(QtCore.QRect(10, 190, 581, 20))
        self.label_54.setStyleSheet("border: 0px solid black;")
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.frame_horario_2)
        self.label_55.setGeometry(QtCore.QRect(10, 290, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setStyleSheet("border: 0px solid black;")
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.frame_horario_2)
        self.label_56.setGeometry(QtCore.QRect(10, 260, 581, 20))
        self.label_56.setStyleSheet("border: 0px solid black;")
        self.label_56.setObjectName("label_56")
        self.stackedWidget_2.addWidget(self.page_horario_2)
        self.page_horario_3 = QtWidgets.QWidget()
        self.page_horario_3.setObjectName("page_horario_3")
        self.frame_horario_3 = QtWidgets.QFrame(self.page_horario_3)
        self.frame_horario_3.setGeometry(QtCore.QRect(20, 10, 601, 341))
        self.frame_horario_3.setStyleSheet("QFrame{\n"
"background-color: rgb(59, 59, 59);\n"
"border: 2px solid black\n"
";}\n"
"")
        self.frame_horario_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_horario_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_horario_3.setObjectName("frame_horario_3")
        self.label_57 = QtWidgets.QLabel(self.frame_horario_3)
        self.label_57.setGeometry(QtCore.QRect(10, 10, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setStyleSheet("border: 0px solid black;")
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.frame_horario_3)
        self.label_58.setGeometry(QtCore.QRect(10, 80, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setStyleSheet("border: 0px solid black;")
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.frame_horario_3)
        self.label_59.setGeometry(QtCore.QRect(10, 150, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setStyleSheet("border: 0px solid black;")
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.frame_horario_3)
        self.label_60.setGeometry(QtCore.QRect(10, 220, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_60.setFont(font)
        self.label_60.setStyleSheet("border: 0px solid black;")
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.frame_horario_3)
        self.label_61.setGeometry(QtCore.QRect(10, 50, 581, 20))
        self.label_61.setStyleSheet("border: 0px solid black;")
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.frame_horario_3)
        self.label_62.setGeometry(QtCore.QRect(10, 120, 581, 20))
        self.label_62.setStyleSheet("border: 0px solid black;")
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.frame_horario_3)
        self.label_63.setGeometry(QtCore.QRect(10, 190, 581, 20))
        self.label_63.setStyleSheet("border: 0px solid black;")
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.frame_horario_3)
        self.label_64.setGeometry(QtCore.QRect(10, 290, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setStyleSheet("border: 0px solid black;")
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.frame_horario_3)
        self.label_65.setGeometry(QtCore.QRect(10, 260, 581, 20))
        self.label_65.setStyleSheet("border: 0px solid black;")
        self.label_65.setObjectName("label_65")
        self.stackedWidget_2.addWidget(self.page_horario_3)
        self.page_horario_4 = QtWidgets.QWidget()
        self.page_horario_4.setObjectName("page_horario_4")
        self.frame_horario_4 = QtWidgets.QFrame(self.page_horario_4)
        self.frame_horario_4.setGeometry(QtCore.QRect(20, 10, 601, 341))
        self.frame_horario_4.setStyleSheet("QFrame{\n"
"background-color: rgb(59, 59, 59);\n"
"border: 2px solid black\n"
";}\n"
"")
        self.frame_horario_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_horario_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_horario_4.setObjectName("frame_horario_4")
        self.label_66 = QtWidgets.QLabel(self.frame_horario_4)
        self.label_66.setGeometry(QtCore.QRect(10, 10, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_66.setFont(font)
        self.label_66.setStyleSheet("border: 0px solid black;")
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.frame_horario_4)
        self.label_67.setGeometry(QtCore.QRect(10, 80, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_67.setFont(font)
        self.label_67.setStyleSheet("border: 0px solid black;")
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(self.frame_horario_4)
        self.label_68.setGeometry(QtCore.QRect(10, 150, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_68.setFont(font)
        self.label_68.setStyleSheet("border: 0px solid black;")
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(self.frame_horario_4)
        self.label_69.setGeometry(QtCore.QRect(10, 220, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_69.setFont(font)
        self.label_69.setStyleSheet("border: 0px solid black;")
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QLabel(self.frame_horario_4)
        self.label_70.setGeometry(QtCore.QRect(10, 50, 581, 20))
        self.label_70.setStyleSheet("border: 0px solid black;")
        self.label_70.setObjectName("label_70")
        self.label_71 = QtWidgets.QLabel(self.frame_horario_4)
        self.label_71.setGeometry(QtCore.QRect(10, 120, 581, 20))
        self.label_71.setStyleSheet("border: 0px solid black;")
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(self.frame_horario_4)
        self.label_72.setGeometry(QtCore.QRect(10, 190, 581, 20))
        self.label_72.setStyleSheet("border: 0px solid black;")
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(self.frame_horario_4)
        self.label_73.setGeometry(QtCore.QRect(10, 290, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_73.setFont(font)
        self.label_73.setStyleSheet("border: 0px solid black;")
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(self.frame_horario_4)
        self.label_74.setGeometry(QtCore.QRect(10, 260, 581, 20))
        self.label_74.setStyleSheet("border: 0px solid black;")
        self.label_74.setObjectName("label_74")
        self.stackedWidget_2.addWidget(self.page_horario_4)
        self.page_horario_5 = QtWidgets.QWidget()
        self.page_horario_5.setObjectName("page_horario_5")
        self.frame_horario_5 = QtWidgets.QFrame(self.page_horario_5)
        self.frame_horario_5.setGeometry(QtCore.QRect(20, 10, 601, 341))
        self.frame_horario_5.setStyleSheet("QFrame{\n"
"background-color: rgb(59, 59, 59);\n"
"border: 2px solid black\n"
";}\n"
"")
        self.frame_horario_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_horario_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_horario_5.setObjectName("frame_horario_5")
        self.label_39 = QtWidgets.QLabel(self.frame_horario_5)
        self.label_39.setGeometry(QtCore.QRect(10, 10, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("border: 0px solid black;")
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.frame_horario_5)
        self.label_40.setGeometry(QtCore.QRect(10, 80, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("border: 0px solid black;")
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.frame_horario_5)
        self.label_41.setGeometry(QtCore.QRect(10, 150, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("border: 0px solid black;")
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.frame_horario_5)
        self.label_42.setGeometry(QtCore.QRect(10, 220, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("border: 0px solid black;")
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.frame_horario_5)
        self.label_43.setGeometry(QtCore.QRect(10, 50, 581, 20))
        self.label_43.setStyleSheet("border: 0px solid black;")
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.frame_horario_5)
        self.label_44.setGeometry(QtCore.QRect(10, 120, 581, 20))
        self.label_44.setStyleSheet("border: 0px solid black;")
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.frame_horario_5)
        self.label_45.setGeometry(QtCore.QRect(10, 190, 581, 20))
        self.label_45.setStyleSheet("border: 0px solid black;")
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.frame_horario_5)
        self.label_46.setGeometry(QtCore.QRect(10, 290, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("border: 0px solid black;")
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.frame_horario_5)
        self.label_47.setGeometry(QtCore.QRect(10, 260, 581, 20))
        self.label_47.setStyleSheet("border: 0px solid black;")
        self.label_47.setObjectName("label_47")
        self.stackedWidget_2.addWidget(self.page_horario_5)
        self.filme_descri = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.filme_descri.setGeometry(QtCore.QRect(240, 110, 511, 181))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.filme_descri.setFont(font)
        self.filme_descri.setStyleSheet("QTextBrowser\n"
"{\n"
"border: 0px solid black;\n"
"}\n"
"")
        self.filme_descri.setObjectName("filme_descri")
        self.filme_name = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.filme_name.setGeometry(QtCore.QRect(330, 0, 251, 101))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.filme_name.setFont(font)
        self.filme_name.setAlignment(QtCore.Qt.AlignCenter)
        self.filme_name.setWordWrap(True)
        self.filme_name.setObjectName("filme_name")
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_2.setGeometry(QtCore.QRect(650, 390, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_3.setGeometry(QtCore.QRect(650, 460, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_4.setGeometry(QtCore.QRect(650, 530, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("")
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_5.setGeometry(QtCore.QRect(650, 590, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("")
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.filme_img = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.filme_img.setGeometry(QtCore.QRect(20, 10, 201, 281))
        self.filme_img.setStyleSheet("QLabel\n"
"{\n"
"border: 3px solid black;\n"
"}\n"
"QLabel:hover\n"
"{\n"
" border: 3px solid yellow;\n"
"}")
        self.filme_img.setText("")
        self.filme_img.setScaledContents(True)
        self.filme_img.setObjectName("filme_img")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton.setGeometry(QtCore.QRect(650, 320, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("")
        self.pushButton.setCheckable(True)
        self.pushButton.setChecked(True)
        self.pushButton.setObjectName("pushButton")
        self.btnBack = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.btnBack.setGeometry(QtCore.QRect(330, 670, 121, 51))
        self.btnBack.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"border: 2px solid black;\n"
"}\n"
"QPushButton:hover{\n"
"border-radius: 10px;\n"
"border: 2px solid white;\n"
"}")
        self.btnBack.setObjectName("btnBack")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setStyleSheet("")
        self.page_3.setObjectName("page_3")
        self.lugares_position = QtWidgets.QFrame(self.page_3)
        self.lugares_position.setGeometry(QtCore.QRect(40, 20, 671, 641))
        self.lugares_position.setStyleSheet("QPushButton{background-color: rgb(72, 154, 4);border: 2px solid black;}QPushButton:hover{border: 2px solid white;}\n"
"QPushButton:checked {background-color: rgb(255, 16, 20);border: 2px solid black;}")
        self.lugares_position.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lugares_position.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lugares_position.setObjectName("lugares_position")
        self.a1 = QtWidgets.QPushButton(self.lugares_position)
        self.a1.setGeometry(QtCore.QRect(10, 20, 131, 101))
        self.a1.setMouseTracking(False)
        self.a1.setStyleSheet("")
        self.a1.setText("")
        self.a1.setCheckable(True)
        self.a1.setChecked(False)
        self.a1.setAutoExclusive(False)
        self.a1.setObjectName("a1")
        self.a2 = QtWidgets.QPushButton(self.lugares_position)
        self.a2.setGeometry(QtCore.QRect(180, 20, 131, 101))
        self.a2.setMouseTracking(False)
        self.a2.setStyleSheet("")
        self.a2.setText("")
        self.a2.setCheckable(True)
        self.a2.setChecked(False)
        self.a2.setObjectName("a2")
        self.a3 = QtWidgets.QPushButton(self.lugares_position)
        self.a3.setGeometry(QtCore.QRect(350, 20, 131, 101))
        self.a3.setMouseTracking(False)
        self.a3.setStyleSheet("")
        self.a3.setText("")
        self.a3.setCheckable(True)
        self.a3.setChecked(False)
        self.a3.setObjectName("a3")
        self.a4 = QtWidgets.QPushButton(self.lugares_position)
        self.a4.setGeometry(QtCore.QRect(520, 20, 131, 101))
        self.a4.setMouseTracking(False)
        self.a4.setStyleSheet("")
        self.a4.setText("")
        self.a4.setCheckable(True)
        self.a4.setChecked(False)
        self.a4.setObjectName("a4")
        self.b1 = QtWidgets.QPushButton(self.lugares_position)
        self.b1.setGeometry(QtCore.QRect(10, 160, 131, 101))
        self.b1.setMouseTracking(False)
        self.b1.setStyleSheet("")
        self.b1.setText("")
        self.b1.setCheckable(True)
        self.b1.setChecked(False)
        self.b1.setObjectName("b1")
        self.b2 = QtWidgets.QPushButton(self.lugares_position)
        self.b2.setGeometry(QtCore.QRect(180, 160, 131, 101))
        self.b2.setMouseTracking(False)
        self.b2.setStyleSheet("")
        self.b2.setText("")
        self.b2.setCheckable(True)
        self.b2.setChecked(False)
        self.b2.setObjectName("b2")
        self.b3 = QtWidgets.QPushButton(self.lugares_position)
        self.b3.setGeometry(QtCore.QRect(350, 170, 131, 101))
        self.b3.setMouseTracking(False)
        self.b3.setStyleSheet("")
        self.b3.setText("")
        self.b3.setCheckable(True)
        self.b3.setChecked(False)
        self.b3.setObjectName("b3")
        self.b4 = QtWidgets.QPushButton(self.lugares_position)
        self.b4.setGeometry(QtCore.QRect(520, 170, 131, 101))
        self.b4.setMouseTracking(False)
        self.b4.setStyleSheet("")
        self.b4.setText("")
        self.b4.setCheckable(True)
        self.b4.setChecked(False)
        self.b4.setObjectName("b4")
        self.c1 = QtWidgets.QPushButton(self.lugares_position)
        self.c1.setGeometry(QtCore.QRect(10, 300, 131, 101))
        self.c1.setMouseTracking(False)
        self.c1.setStyleSheet("")
        self.c1.setText("")
        self.c1.setCheckable(True)
        self.c1.setChecked(False)
        self.c1.setObjectName("c1")
        self.c2 = QtWidgets.QPushButton(self.lugares_position)
        self.c2.setGeometry(QtCore.QRect(180, 300, 131, 101))
        self.c2.setMouseTracking(False)
        self.c2.setStyleSheet("")
        self.c2.setText("")
        self.c2.setCheckable(True)
        self.c2.setChecked(False)
        self.c2.setObjectName("c2")
        self.c3 = QtWidgets.QPushButton(self.lugares_position)
        self.c3.setGeometry(QtCore.QRect(350, 300, 131, 101))
        self.c3.setMouseTracking(False)
        self.c3.setStyleSheet("")
        self.c3.setText("")
        self.c3.setCheckable(True)
        self.c3.setChecked(False)
        self.c3.setObjectName("c3")
        self.c4 = QtWidgets.QPushButton(self.lugares_position)
        self.c4.setGeometry(QtCore.QRect(520, 300, 131, 101))
        self.c4.setMouseTracking(False)
        self.c4.setStyleSheet("")
        self.c4.setText("")
        self.c4.setCheckable(True)
        self.c4.setChecked(False)
        self.c4.setObjectName("c4")
        self.label_12 = QtWidgets.QLabel(self.lugares_position)
        self.label_12.setGeometry(QtCore.QRect(20, 440, 611, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background: rgb(150, 16, 36)")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.pushButton_7 = QtWidgets.QPushButton(self.lugares_position)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 490, 121, 51))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"background-color: rgb(229, 229, 0);\n"
"border-radius: 10px;\n"
"border: 2px solid black;\n"
"}\n"
"QPushButton:hover{\n"
"background: white;\n"
"border-radius: 10px;\n"
"border: 2px solid black;\n"
"}\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.lugares_position)
        self.pushButton_6.setGeometry(QtCore.QRect(510, 490, 121, 51))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"background-color: rgb(229, 229, 0);\n"
"border-radius: 10px;\n"
"border: 2px solid black;\n"
"}\n"
"QPushButton:hover{\n"
"background: white;\n"
"border-radius: 10px;\n"
"border: 2px solid black;\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setStyleSheet("QLineEdit{\n"
"background: white;\n"
"border: 2px solid black;\n"
"border-radius: 15px\n"
"}\n"
"")
        self.page_4.setObjectName("page_4")
        self.lineEdit = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit.setGeometry(QtCore.QRect(220, 120, 301, 61))
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 200, 301, 61))
        self.lineEdit_2.setStyleSheet("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_8 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_8.setGeometry(QtCore.QRect(390, 280, 141, 51))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"background-color: rgb(229, 229, 0);\n"
"border-radius: 10px;\n"
"border: 2px solid black;\n"
"}\n"
"QPushButton:hover{\n"
"background: white;\n"
"border-radius: 10px;\n"
"border: 2px solid black;\n"
"}\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_9.setGeometry(QtCore.QRect(220, 280, 141, 51))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"background-color: rgb(229, 229, 0);\n"
"border-radius: 10px;\n"
"border: 2px solid black;\n"
"}\n"
"QPushButton:hover{\n"
"background: white;\n"
"border-radius: 10px;\n"
"border: 2px solid black;\n"
"}\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_13 = QtWidgets.QLabel(self.page_4)
        self.label_13.setGeometry(QtCore.QRect(-60, 0, 871, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background: rgb(61, 140, 61);\n"
"border-radius: 10px;\n"
"border: 2px solid black;\n"
"color: white")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.filme_img_2 = QtWidgets.QLabel(self.page_4)
        self.filme_img_2.setGeometry(QtCore.QRect(10, 100, 201, 281))
        self.filme_img_2.setStyleSheet("QLabel\n"
"{\n"
"border: 3px solid black;\n"
"}\n"
"QLabel:hover\n"
"{\n"
" border: 3px solid yellow;\n"
"}")
        self.filme_img_2.setText("")
        self.filme_img_2.setScaledContents(True)
        self.filme_img_2.setObjectName("filme_img_2")
        self.filme_name_2 = QtWidgets.QLabel(self.page_4)
        self.filme_name_2.setGeometry(QtCore.QRect(0, 400, 251, 101))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.filme_name_2.setFont(font)
        self.filme_name_2.setAlignment(QtCore.Qt.AlignCenter)
        self.filme_name_2.setWordWrap(True)
        self.filme_name_2.setObjectName("filme_name_2")
        self.label_14 = QtWidgets.QLabel(self.page_4)
        self.label_14.setGeometry(QtCore.QRect(270, 360, 441, 161))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background: white;\n"
"border: 2px solid black;")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.stackedWidget.addWidget(self.page_4)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 804, 755, 40))
        self.frame_3.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_3.setStyleSheet("background-color: rgb(59, 59, 59);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cinema APP"))
        self.cartazLabel.setText(_translate("MainWindow", "EM CARTAZ"))
        self.label_11.setText(_translate("MainWindow", "____________________________________________________________________________________________________________________________"))
        self.label.setText(_translate("MainWindow", "Sala 01"))
        self.label_2.setText(_translate("MainWindow", "Sala 02"))
        self.label_3.setText(_translate("MainWindow", "Sala 03"))
        self.label_4.setText(_translate("MainWindow", "Sala 04"))
        self.label_5.setText(_translate("MainWindow", "_______________________________________________________________________________________________________________"))
        self.label_6.setText(_translate("MainWindow", "_______________________________________________________________________________________________________________"))
        self.label_7.setText(_translate("MainWindow", "_______________________________________________________________________________________________________________"))
        self.label_8.setText(_translate("MainWindow", "Sala 05"))
        self.label_9.setText(_translate("MainWindow", "_______________________________________________________________________________________________________________"))
        self.label_48.setText(_translate("MainWindow", "Sala 01"))
        self.label_49.setText(_translate("MainWindow", "Sala 02"))
        self.label_50.setText(_translate("MainWindow", "Sala 03"))
        self.label_51.setText(_translate("MainWindow", "Sala 04"))
        self.label_52.setText(_translate("MainWindow", "_______________________________________________________________________________________________________________"))
        self.label_53.setText(_translate("MainWindow", "_______________________________________________________________________________________________________________"))
        self.label_54.setText(_translate("MainWindow", "_______________________________________________________________________________________________________________"))
        self.label_55.setText(_translate("MainWindow", "Sala 05"))
        self.label_56.setText(_translate("MainWindow", "_______________________________________________________________________________________________________________"))
        self.label_57.setText(_translate("MainWindow", "Sala 01"))
        self.label_58.setText(_translate("MainWindow", "Sala 02"))
        self.label_59.setText(_translate("MainWindow", "Sala 03"))
        self.label_60.setText(_translate("MainWindow", "Sala 04"))
        self.label_61.setText(_translate("MainWindow", "_______________________________________________________________________________________________________________"))
        self.label_62.setText(_translate("MainWindow", "_______________________________________________________________________________________________________________"))
        self.label_63.setText(_translate("MainWindow", "_______________________________________________________________________________________________________________"))
        self.label_64.setText(_translate("MainWindow", "Sala 05"))
        self.label_65.setText(_translate("MainWindow", "_______________________________________________________________________________________________________________"))
        self.label_66.setText(_translate("MainWindow", "Sala 01"))
        self.label_67.setText(_translate("MainWindow", "Sala 02"))
        self.label_68.setText(_translate("MainWindow", "Sala 03"))
        self.label_69.setText(_translate("MainWindow", "Sala 04"))
        self.label_70.setText(_translate("MainWindow", "_______________________________________________________________________________________________________________"))
        self.label_71.setText(_translate("MainWindow", "_______________________________________________________________________________________________________________"))
        self.label_72.setText(_translate("MainWindow", "_______________________________________________________________________________________________________________"))
        self.label_73.setText(_translate("MainWindow", "Sala 05"))
        self.label_74.setText(_translate("MainWindow", "_______________________________________________________________________________________________________________"))
        self.label_39.setText(_translate("MainWindow", "Sala 01"))
        self.label_40.setText(_translate("MainWindow", "Sala 02"))
        self.label_41.setText(_translate("MainWindow", "Sala 03"))
        self.label_42.setText(_translate("MainWindow", "Sala 04"))
        self.label_43.setText(_translate("MainWindow", "_______________________________________________________________________________________________________________"))
        self.label_44.setText(_translate("MainWindow", "_______________________________________________________________________________________________________________"))
        self.label_45.setText(_translate("MainWindow", "_______________________________________________________________________________________________________________"))
        self.label_46.setText(_translate("MainWindow", "Sala 05"))
        self.label_47.setText(_translate("MainWindow", "_______________________________________________________________________________________________________________"))
        self.filme_descri.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">DESCRIÇÃO DO FILME</p></body></html>"))
        self.filme_name.setText(_translate("MainWindow", "NOME DO FILME"))
        self.pushButton_2.setText(_translate("MainWindow", "01/06"))
        self.pushButton_3.setText(_translate("MainWindow", "02/06"))
        self.pushButton_4.setText(_translate("MainWindow", "03/06"))
        self.pushButton_5.setText(_translate("MainWindow", "04/06"))
        self.pushButton.setText(_translate("MainWindow", "31/05"))
        self.btnBack.setText(_translate("MainWindow", "VOLTAR"))
        self.label_12.setText(_translate("MainWindow", "TELA"))
        self.pushButton_7.setText(_translate("MainWindow", "VOLTAR"))
        self.pushButton_6.setText(_translate("MainWindow", "CONTINUAR"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "NOME COMPLETO"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "TELEFONE"))
        self.pushButton_8.setText(_translate("MainWindow", "CONFIRMAR COMPRA"))
        self.pushButton_9.setText(_translate("MainWindow", "CANCELAR"))
        self.label_13.setText(_translate("MainWindow", "DADOS DO CLIENTE"))
        self.filme_name_2.setText(_translate("MainWindow", "NOME DO FILME"))
        self.label_14.setText(_translate("MainWindow", "INFORMAÇÕES DO INGRESSO:\n"
""))


